interface: "vcan0"             # name of your can interface
receiver_interval_sec: 1.0   # 1/hz of your messages
sender_timeout_sec: 1.0      # time between messages before socketcan sends a timeout warning
enable_can_fd: false